### ISSUE TITLE
[Feature Request] Accepting esi evetech killboard links.

### ISSUE THREAD

**Issue by crius-al** [ppfeufer/aa-srp#118] opened 2023-07-23 01:45 UTC
### Context
I would expect this feature to be useful if the kill doesn't show up on zkillboard, and we don't want the kill to show up on zkillboard.

### Describe the feature you have in mind

I would like the srp to accept esi evetech links, like https://github.com/dysath/seat-srp seems to.

### Additional context

These are the links you can get in game by copying the external kill link.

I made minor modifications to a couple files to accept the kill links. This might help explain what I'm hoping for.

[constants.txt](https://github.com/ppfeufer/aa-srp/files/12137539/constants.txt)
[form.txt](https://github.com/ppfeufer/aa-srp/files/12137540/form.txt)

**Comment by ppfeufer** [comment] 2023-07-23 07:51
Duplicate of: https://github.com/ppfeufer/aa-srp/issues/55

**Closed by ppfeufer** 2023-07-23 07:51 UTC
